name: vision-flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - pandas
  - pillow
  - poppler  # Required for pdf2image
  - pip:
    - google-cloud-vision>=3.0.0
    - openai>=1.12.0
    - python-dotenv>=0.19.0
    - pdf2image>=1.17.0
    - pymongo>=4.0.0
    - opencv-python>=4.5.0